DROP TABLE IF EXISTS subscriptions;
CREATE TABLE IF NOT EXISTS subscriptions (
	id SERIAL PRIMARY KEY,
	user_id VARCHAR (255) NOT NULL,
	status BOOLEAN NOT NULL DEFAULT (TRUE),
	is_admin BOOLEAN NOT NULL DEFAULT (FALSE)
);

DROP TABLE IF EXISTS languages;
CREATE TABLE IF NOT EXISTS languages (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50)
);

DROP TABLE IF EXISTS themes;
CREATE TABLE IF NOT EXISTS themes (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50),
	lang_id BIGINT UNSIGNED NOT NULL,
	description VARCHAR(255),
	FOREIGN KEY (lang_id) REFERENCES languages(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

DROP TABLE IF EXISTS photo_albums;
CREATE TABLE IF NOT EXISTS photo_albums (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50),
	themes_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (themes_id) REFERENCES themes(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

DROP TABLE IF EXISTS photos;
CREATE TABLE IF NOT EXISTS photos (
	id SERIAL PRIMARY KEY,
	ph_album_id BIGINT UNSIGNED NOT NULL,
	media_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (ph_album_id) REFERENCES photo_albums(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (media_id) REFERENCES media(id) ON UPDATE CASCADE ON DELETE RESTRICT
); 

DROP TABLE IF EXISTS pdf_albums;
CREATE TABLE IF NOT EXISTS pdf_albums (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50),
	themes_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (themes_id) REFERENCES themes(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

DROP TABLE IF EXISTS pdfs;
CREATE TABLE IF NOT EXISTS pdfs (
	id SERIAL PRIMARY KEY,
	pdf_album_id BIGINT UNSIGNED NOT NULL,
	media_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (pdf_album_id) REFERENCES pdf_albums(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (media_id) REFERENCES media(id) ON UPDATE CASCADE ON DELETE RESTRICT
); 

DROP TABLE IF EXISTS quiz_albums;
CREATE TABLE IF NOT EXISTS quiz_albums (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50),
	themes_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (themes_id) REFERENCES themes(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

DROP TABLE IF EXISTS quiz;
CREATE TABLE IF NOT EXISTS quiz (
	id SERIAL PRIMARY KEY,
	quiz_album_id BIGINT UNSIGNED NOT NULL,
	media_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (quiz_album_id) REFERENCES quiz_albums(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (media_id) REFERENCES media(id) ON UPDATE CASCADE ON DELETE RESTRICT
); 

DROP TABLE IF EXISTS media_types;
CREATE TABLE IF NOT EXISTS media_types (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS media;
CREATE TABLE IF NOT EXISTS media (
	id SERIAL PRIMARY KEY,
    media_type_id BIGINT UNSIGNED NOT NULL,
    themes_id BIGINT UNSIGNED NOT NULL,
  	body text,
    filename VARCHAR(255),
    `size` INT,
	metadata JSON,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (themes_id) REFERENCES themes(id),
    FOREIGN KEY (media_type_id) REFERENCES media_types(id)
);


